### ISSUE TITLE
Required expects boolean, wider options available in Mongoose

### ISSUE THREAD

**Issue by WazzaJB** [lstkz/ts-mongoose#44]
Hey,

New to TS, but thanks for the handy package when it comes to Mongoose!

I'm unable however to define custom required messages as so:

```required: [true, 'Email address is required']```

Mongoose accepts a wider amount of required options than just a bool: https://mongoosejs.com/docs/api.html#schematype_SchemaType-required

I have forked and attempted resolution here myself but sadly lack the TS experience at the moment.

I have also worked round this at the moment:

```required: [true, 'Email address is required'] as any```

Thanks again, sorry if I missed something or am doing something wrong!

**Comment by lchimaru** [comment]
For now our package is not supporting such way of providing required option. But you can try:
```ts
required: [true, 'Email address is required'] as unknown as true
```
That should let typescript treat this prop as required while mongoose will create required property with custom message.
