### ISSUE TITLE
push 0.0.22 to npm

### ISSUE THREAD

**Issue by blackmad** [lstkz/ts-mongoose#54]
Hi,

I'd like to use the connection parameter in typedModel, but I think it's not in 0.0.21 and I don't see 0.0.22 on npmjs at the moment. Would it be possible to push a version bump?

Thanks,
David

**Comment by garethfentimen** [comment]
right now I am using: "ts-mongoose": "git+https://github.com/lstkz/ts-mongoose.git"

**Comment by lchimaru** [comment]
It took some time, but newest version is now available on npm.
