### ISSUE TITLE
Creating model with {timestamps: true} set

### ISSUE THREAD

**Issue by LarsOlt** [lstkz/ts-mongoose#60]
I can't use the create method on a model with the {timestamps: true} option set, because TS wants me to set "createdAt" and "updatedAt" which are not optional fields. How do I get this to work?

![image](https://user-images.githubusercontent.com/32353679/89112759-2a532200-d468-11ea-81ba-cdb01ee8b1e9.png)

**Comment by LarsOlt** [comment]
Fixed it by casting the object as any type. 

![image](https://user-images.githubusercontent.com/32353679/89112818-d85ecc00-d468-11ea-872f-a9c2e8d02ab7.png)

**Comment by stabback** [comment]
@lstkz It may be worth visiting this issue or adding the workaround to the documentation.  I'd like to ensure type safety when creating an instance of the model.
